AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  DatalogFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: datalog.lambda_handler
      Runtime: python3.6
      CodeUri: lambda/datalog.py
      MemorySize: 256
      Timeout: 15
      Policies: AWSLambdaKinesisExecutionRole
      Events:
        DataStream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt DataStream.Arn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  DataStream:
    Type: AWS::Kinesis::Stream
    Properties: 
      Name: datastream
      ShardCount: 1
      Tags:
        - 
          Key: 'Project'
          Value: 'SEIS665'